ALTER TABLE service_requests MODIFY COLUMN lat DECIMAL(10, 8) NULL DEFAULT NULL;

ALTER TABLE service_requests MODIFY COLUMN lng DECIMAL(11, 8) NULL DEFAULT NULL;

ALTER TABLE managers MODIFY COLUMN account_number VARCHAR(50) NULL DEFAULT NULL;
